# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b28504982f6dc508e367f471fc16ba0"
name = "product-recommendations"
application_url = "https://northwest-myself-succeed-obtain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zohaib-dev-2.myshopify.com"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,write_content,write_products"

[auth]
redirect_urls = [ "https://northwest-myself-succeed-obtain.trycloudflare.com/auth/callback" ]

[pos]
embedded = false

[app_proxy]
url = "https://northwest-myself-succeed-obtain.trycloudflare.com/api/recommendations"
subpath = "recommendations"
prefix = "apps"
